// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using Tasky.CurrencyService.Samples;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace Tasky.CurrencyService.Samples;

public class SampleDto
{
    public int Value { get; set; }
}
